### PR TITLE
Added sane fallback value for stylist themes paths

### PR DESCRIPTION
**Pull request by mvdstam**

### CODE REVIEW

**Comment by mvdstam** [comment]
Just thinking out loud here -- but shouldn't the `stylist.themes.paths` be ignored and the `asgard:core.themes_path` be used instead?

**Comment by nWidart** [comment]
I was thinking of that too, but I'm thinking I'm going to ditch the core.theme settings, since Stylist already has this setting.

**Comment by nWidart** [comment]
Please send a PR against develop next time.

**Comment by nWidart** [comment]
Thanks, done manually in [1.5.0](https://github.com/AsgardCms/Setting/releases/tag/1.5.0)

**Pull request closed without merging**
